// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FugasColumns holds the columns for the "fugas" table.
	FugasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "number", Type: field.TypeInt32},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// FugasTable holds the schema information for the "fugas" table.
	FugasTable = &schema.Table{
		Name:       "fugas",
		Columns:    FugasColumns,
		PrimaryKey: []*schema.Column{FugasColumns[0]},
	}
	// HogesColumns holds the columns for the "hoges" table.
	HogesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "number", Type: field.TypeInt32},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// HogesTable holds the schema information for the "hoges" table.
	HogesTable = &schema.Table{
		Name:       "hoges",
		Columns:    HogesColumns,
		PrimaryKey: []*schema.Column{HogesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FugasTable,
		HogesTable,
	}
)

func init() {
}
