// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"
	"xxx/ent/schema"
	"xxx/ent/xxx"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	xxxFields := schema.Xxx{}.Fields()
	_ = xxxFields
	// xxxDescCreatedAt is the schema descriptor for createdAt field.
	xxxDescCreatedAt := xxxFields[3].Descriptor()
	// xxx.DefaultCreatedAt holds the default value on creation for the createdAt field.
	xxx.DefaultCreatedAt = xxxDescCreatedAt.Default.(func() time.Time)
	// xxxDescUpdatedAt is the schema descriptor for updatedAt field.
	xxxDescUpdatedAt := xxxFields[4].Descriptor()
	// xxx.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	xxx.DefaultUpdatedAt = xxxDescUpdatedAt.Default.(func() time.Time)
	// xxx.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	xxx.UpdateDefaultUpdatedAt = xxxDescUpdatedAt.UpdateDefault.(func() time.Time)
}
