// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"xxx/app/infra/ent/ent/migrate"

	"xxx/app/infra/ent/ent/xxx"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Xxx is the client for interacting with the Xxx builders.
	Xxx *XxxClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Xxx = NewXxxClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Xxx:    NewXxxClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config: cfg,
		Xxx:    NewXxxClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Xxx.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Xxx.Use(hooks...)
}

// XxxClient is a client for the Xxx schema.
type XxxClient struct {
	config
}

// NewXxxClient returns a client for the Xxx from the given config.
func NewXxxClient(c config) *XxxClient {
	return &XxxClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `xxx.Hooks(f(g(h())))`.
func (c *XxxClient) Use(hooks ...Hook) {
	c.hooks.Xxx = append(c.hooks.Xxx, hooks...)
}

// Create returns a create builder for Xxx.
func (c *XxxClient) Create() *XxxCreate {
	mutation := newXxxMutation(c.config, OpCreate)
	return &XxxCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Xxx entities.
func (c *XxxClient) CreateBulk(builders ...*XxxCreate) *XxxCreateBulk {
	return &XxxCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Xxx.
func (c *XxxClient) Update() *XxxUpdate {
	mutation := newXxxMutation(c.config, OpUpdate)
	return &XxxUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *XxxClient) UpdateOne(x *Xxx) *XxxUpdateOne {
	mutation := newXxxMutation(c.config, OpUpdateOne, withXxx(x))
	return &XxxUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *XxxClient) UpdateOneID(id uuid.UUID) *XxxUpdateOne {
	mutation := newXxxMutation(c.config, OpUpdateOne, withXxxID(id))
	return &XxxUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Xxx.
func (c *XxxClient) Delete() *XxxDelete {
	mutation := newXxxMutation(c.config, OpDelete)
	return &XxxDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *XxxClient) DeleteOne(x *Xxx) *XxxDeleteOne {
	return c.DeleteOneID(x.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *XxxClient) DeleteOneID(id uuid.UUID) *XxxDeleteOne {
	builder := c.Delete().Where(xxx.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &XxxDeleteOne{builder}
}

// Query returns a query builder for Xxx.
func (c *XxxClient) Query() *XxxQuery {
	return &XxxQuery{
		config: c.config,
	}
}

// Get returns a Xxx entity by its id.
func (c *XxxClient) Get(ctx context.Context, id uuid.UUID) (*Xxx, error) {
	return c.Query().Where(xxx.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *XxxClient) GetX(ctx context.Context, id uuid.UUID) *Xxx {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *XxxClient) Hooks() []Hook {
	return c.hooks.Xxx
}
