// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sync"
	"time"
	"xxx/app/infra/ent/ent/predicate"
	"xxx/app/infra/ent/ent/xxx"

	"github.com/google/uuid"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeXxx = "Xxx"
)

// XxxMutation represents an operation that mutates the Xxx nodes in the graph.
type XxxMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	name          *string
	number        *int
	addnumber     *int
	createdAt     *time.Time
	updatedAt     *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Xxx, error)
	predicates    []predicate.Xxx
}

var _ ent.Mutation = (*XxxMutation)(nil)

// xxxOption allows management of the mutation configuration using functional options.
type xxxOption func(*XxxMutation)

// newXxxMutation creates new mutation for the Xxx entity.
func newXxxMutation(c config, op Op, opts ...xxxOption) *XxxMutation {
	m := &XxxMutation{
		config:        c,
		op:            op,
		typ:           TypeXxx,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withXxxID sets the ID field of the mutation.
func withXxxID(id uuid.UUID) xxxOption {
	return func(m *XxxMutation) {
		var (
			err   error
			once  sync.Once
			value *Xxx
		)
		m.oldValue = func(ctx context.Context) (*Xxx, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Xxx.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withXxx sets the old Xxx of the mutation.
func withXxx(node *Xxx) xxxOption {
	return func(m *XxxMutation) {
		m.oldValue = func(context.Context) (*Xxx, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m XxxMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m XxxMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Xxx entities.
func (m *XxxMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *XxxMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetName sets the "name" field.
func (m *XxxMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *XxxMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Xxx entity.
// If the Xxx object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *XxxMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ClearName clears the value of the "name" field.
func (m *XxxMutation) ClearName() {
	m.name = nil
	m.clearedFields[xxx.FieldName] = struct{}{}
}

// NameCleared returns if the "name" field was cleared in this mutation.
func (m *XxxMutation) NameCleared() bool {
	_, ok := m.clearedFields[xxx.FieldName]
	return ok
}

// ResetName resets all changes to the "name" field.
func (m *XxxMutation) ResetName() {
	m.name = nil
	delete(m.clearedFields, xxx.FieldName)
}

// SetNumber sets the "number" field.
func (m *XxxMutation) SetNumber(i int) {
	m.number = &i
	m.addnumber = nil
}

// Number returns the value of the "number" field in the mutation.
func (m *XxxMutation) Number() (r int, exists bool) {
	v := m.number
	if v == nil {
		return
	}
	return *v, true
}

// OldNumber returns the old "number" field's value of the Xxx entity.
// If the Xxx object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *XxxMutation) OldNumber(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNumber: %w", err)
	}
	return oldValue.Number, nil
}

// AddNumber adds i to the "number" field.
func (m *XxxMutation) AddNumber(i int) {
	if m.addnumber != nil {
		*m.addnumber += i
	} else {
		m.addnumber = &i
	}
}

// AddedNumber returns the value that was added to the "number" field in this mutation.
func (m *XxxMutation) AddedNumber() (r int, exists bool) {
	v := m.addnumber
	if v == nil {
		return
	}
	return *v, true
}

// ClearNumber clears the value of the "number" field.
func (m *XxxMutation) ClearNumber() {
	m.number = nil
	m.addnumber = nil
	m.clearedFields[xxx.FieldNumber] = struct{}{}
}

// NumberCleared returns if the "number" field was cleared in this mutation.
func (m *XxxMutation) NumberCleared() bool {
	_, ok := m.clearedFields[xxx.FieldNumber]
	return ok
}

// ResetNumber resets all changes to the "number" field.
func (m *XxxMutation) ResetNumber() {
	m.number = nil
	m.addnumber = nil
	delete(m.clearedFields, xxx.FieldNumber)
}

// SetCreatedAt sets the "createdAt" field.
func (m *XxxMutation) SetCreatedAt(t time.Time) {
	m.createdAt = &t
}

// CreatedAt returns the value of the "createdAt" field in the mutation.
func (m *XxxMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.createdAt
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "createdAt" field's value of the Xxx entity.
// If the Xxx object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *XxxMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "createdAt" field.
func (m *XxxMutation) ResetCreatedAt() {
	m.createdAt = nil
}

// SetUpdatedAt sets the "updatedAt" field.
func (m *XxxMutation) SetUpdatedAt(t time.Time) {
	m.updatedAt = &t
}

// UpdatedAt returns the value of the "updatedAt" field in the mutation.
func (m *XxxMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updatedAt
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updatedAt" field's value of the Xxx entity.
// If the Xxx object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *XxxMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updatedAt" field.
func (m *XxxMutation) ResetUpdatedAt() {
	m.updatedAt = nil
}

// Where appends a list predicates to the XxxMutation builder.
func (m *XxxMutation) Where(ps ...predicate.Xxx) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *XxxMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Xxx).
func (m *XxxMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *XxxMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.name != nil {
		fields = append(fields, xxx.FieldName)
	}
	if m.number != nil {
		fields = append(fields, xxx.FieldNumber)
	}
	if m.createdAt != nil {
		fields = append(fields, xxx.FieldCreatedAt)
	}
	if m.updatedAt != nil {
		fields = append(fields, xxx.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *XxxMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case xxx.FieldName:
		return m.Name()
	case xxx.FieldNumber:
		return m.Number()
	case xxx.FieldCreatedAt:
		return m.CreatedAt()
	case xxx.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *XxxMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case xxx.FieldName:
		return m.OldName(ctx)
	case xxx.FieldNumber:
		return m.OldNumber(ctx)
	case xxx.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case xxx.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Xxx field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *XxxMutation) SetField(name string, value ent.Value) error {
	switch name {
	case xxx.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case xxx.FieldNumber:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNumber(v)
		return nil
	case xxx.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case xxx.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Xxx field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *XxxMutation) AddedFields() []string {
	var fields []string
	if m.addnumber != nil {
		fields = append(fields, xxx.FieldNumber)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *XxxMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case xxx.FieldNumber:
		return m.AddedNumber()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *XxxMutation) AddField(name string, value ent.Value) error {
	switch name {
	case xxx.FieldNumber:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddNumber(v)
		return nil
	}
	return fmt.Errorf("unknown Xxx numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *XxxMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(xxx.FieldName) {
		fields = append(fields, xxx.FieldName)
	}
	if m.FieldCleared(xxx.FieldNumber) {
		fields = append(fields, xxx.FieldNumber)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *XxxMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *XxxMutation) ClearField(name string) error {
	switch name {
	case xxx.FieldName:
		m.ClearName()
		return nil
	case xxx.FieldNumber:
		m.ClearNumber()
		return nil
	}
	return fmt.Errorf("unknown Xxx nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *XxxMutation) ResetField(name string) error {
	switch name {
	case xxx.FieldName:
		m.ResetName()
		return nil
	case xxx.FieldNumber:
		m.ResetNumber()
		return nil
	case xxx.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case xxx.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Xxx field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *XxxMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *XxxMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *XxxMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *XxxMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *XxxMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *XxxMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *XxxMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Xxx unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *XxxMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Xxx edge %s", name)
}
