// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"xxx/app/infra/ent/ent/predicate"
	"xxx/app/infra/ent/ent/xxx"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// XxxQuery is the builder for querying Xxx entities.
type XxxQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.Xxx
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the XxxQuery builder.
func (xq *XxxQuery) Where(ps ...predicate.Xxx) *XxxQuery {
	xq.predicates = append(xq.predicates, ps...)
	return xq
}

// Limit adds a limit step to the query.
func (xq *XxxQuery) Limit(limit int) *XxxQuery {
	xq.limit = &limit
	return xq
}

// Offset adds an offset step to the query.
func (xq *XxxQuery) Offset(offset int) *XxxQuery {
	xq.offset = &offset
	return xq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (xq *XxxQuery) Unique(unique bool) *XxxQuery {
	xq.unique = &unique
	return xq
}

// Order adds an order step to the query.
func (xq *XxxQuery) Order(o ...OrderFunc) *XxxQuery {
	xq.order = append(xq.order, o...)
	return xq
}

// First returns the first Xxx entity from the query.
// Returns a *NotFoundError when no Xxx was found.
func (xq *XxxQuery) First(ctx context.Context) (*Xxx, error) {
	nodes, err := xq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{xxx.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (xq *XxxQuery) FirstX(ctx context.Context) *Xxx {
	node, err := xq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Xxx ID from the query.
// Returns a *NotFoundError when no Xxx ID was found.
func (xq *XxxQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = xq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{xxx.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (xq *XxxQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := xq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Xxx entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one Xxx entity is not found.
// Returns a *NotFoundError when no Xxx entities are found.
func (xq *XxxQuery) Only(ctx context.Context) (*Xxx, error) {
	nodes, err := xq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{xxx.Label}
	default:
		return nil, &NotSingularError{xxx.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (xq *XxxQuery) OnlyX(ctx context.Context) *Xxx {
	node, err := xq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Xxx ID in the query.
// Returns a *NotSingularError when exactly one Xxx ID is not found.
// Returns a *NotFoundError when no entities are found.
func (xq *XxxQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = xq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{xxx.Label}
	default:
		err = &NotSingularError{xxx.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (xq *XxxQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := xq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Xxxes.
func (xq *XxxQuery) All(ctx context.Context) ([]*Xxx, error) {
	if err := xq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return xq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (xq *XxxQuery) AllX(ctx context.Context) []*Xxx {
	nodes, err := xq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Xxx IDs.
func (xq *XxxQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := xq.Select(xxx.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (xq *XxxQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := xq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (xq *XxxQuery) Count(ctx context.Context) (int, error) {
	if err := xq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return xq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (xq *XxxQuery) CountX(ctx context.Context) int {
	count, err := xq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (xq *XxxQuery) Exist(ctx context.Context) (bool, error) {
	if err := xq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return xq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (xq *XxxQuery) ExistX(ctx context.Context) bool {
	exist, err := xq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the XxxQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (xq *XxxQuery) Clone() *XxxQuery {
	if xq == nil {
		return nil
	}
	return &XxxQuery{
		config:     xq.config,
		limit:      xq.limit,
		offset:     xq.offset,
		order:      append([]OrderFunc{}, xq.order...),
		predicates: append([]predicate.Xxx{}, xq.predicates...),
		// clone intermediate query.
		sql:  xq.sql.Clone(),
		path: xq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Xxx.Query().
//		GroupBy(xxx.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (xq *XxxQuery) GroupBy(field string, fields ...string) *XxxGroupBy {
	group := &XxxGroupBy{config: xq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := xq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return xq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Xxx.Query().
//		Select(xxx.FieldName).
//		Scan(ctx, &v)
//
func (xq *XxxQuery) Select(fields ...string) *XxxSelect {
	xq.fields = append(xq.fields, fields...)
	return &XxxSelect{XxxQuery: xq}
}

func (xq *XxxQuery) prepareQuery(ctx context.Context) error {
	for _, f := range xq.fields {
		if !xxx.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if xq.path != nil {
		prev, err := xq.path(ctx)
		if err != nil {
			return err
		}
		xq.sql = prev
	}
	return nil
}

func (xq *XxxQuery) sqlAll(ctx context.Context) ([]*Xxx, error) {
	var (
		nodes = []*Xxx{}
		_spec = xq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &Xxx{config: xq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, xq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (xq *XxxQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := xq.querySpec()
	return sqlgraph.CountNodes(ctx, xq.driver, _spec)
}

func (xq *XxxQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := xq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (xq *XxxQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   xxx.Table,
			Columns: xxx.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: xxx.FieldID,
			},
		},
		From:   xq.sql,
		Unique: true,
	}
	if unique := xq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := xq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, xxx.FieldID)
		for i := range fields {
			if fields[i] != xxx.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := xq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := xq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := xq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := xq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (xq *XxxQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(xq.driver.Dialect())
	t1 := builder.Table(xxx.Table)
	columns := xq.fields
	if len(columns) == 0 {
		columns = xxx.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if xq.sql != nil {
		selector = xq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range xq.predicates {
		p(selector)
	}
	for _, p := range xq.order {
		p(selector)
	}
	if offset := xq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := xq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// XxxGroupBy is the group-by builder for Xxx entities.
type XxxGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (xgb *XxxGroupBy) Aggregate(fns ...AggregateFunc) *XxxGroupBy {
	xgb.fns = append(xgb.fns, fns...)
	return xgb
}

// Scan applies the group-by query and scans the result into the given value.
func (xgb *XxxGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := xgb.path(ctx)
	if err != nil {
		return err
	}
	xgb.sql = query
	return xgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (xgb *XxxGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := xgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (xgb *XxxGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(xgb.fields) > 1 {
		return nil, errors.New("ent: XxxGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := xgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (xgb *XxxGroupBy) StringsX(ctx context.Context) []string {
	v, err := xgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (xgb *XxxGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = xgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xxx.Label}
	default:
		err = fmt.Errorf("ent: XxxGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (xgb *XxxGroupBy) StringX(ctx context.Context) string {
	v, err := xgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (xgb *XxxGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(xgb.fields) > 1 {
		return nil, errors.New("ent: XxxGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := xgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (xgb *XxxGroupBy) IntsX(ctx context.Context) []int {
	v, err := xgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (xgb *XxxGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = xgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xxx.Label}
	default:
		err = fmt.Errorf("ent: XxxGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (xgb *XxxGroupBy) IntX(ctx context.Context) int {
	v, err := xgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (xgb *XxxGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(xgb.fields) > 1 {
		return nil, errors.New("ent: XxxGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := xgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (xgb *XxxGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := xgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (xgb *XxxGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = xgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xxx.Label}
	default:
		err = fmt.Errorf("ent: XxxGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (xgb *XxxGroupBy) Float64X(ctx context.Context) float64 {
	v, err := xgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (xgb *XxxGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(xgb.fields) > 1 {
		return nil, errors.New("ent: XxxGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := xgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (xgb *XxxGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := xgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (xgb *XxxGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = xgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xxx.Label}
	default:
		err = fmt.Errorf("ent: XxxGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (xgb *XxxGroupBy) BoolX(ctx context.Context) bool {
	v, err := xgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (xgb *XxxGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range xgb.fields {
		if !xxx.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := xgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := xgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (xgb *XxxGroupBy) sqlQuery() *sql.Selector {
	selector := xgb.sql.Select()
	aggregation := make([]string, 0, len(xgb.fns))
	for _, fn := range xgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(xgb.fields)+len(xgb.fns))
		for _, f := range xgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(xgb.fields...)...)
}

// XxxSelect is the builder for selecting fields of Xxx entities.
type XxxSelect struct {
	*XxxQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (xs *XxxSelect) Scan(ctx context.Context, v interface{}) error {
	if err := xs.prepareQuery(ctx); err != nil {
		return err
	}
	xs.sql = xs.XxxQuery.sqlQuery(ctx)
	return xs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (xs *XxxSelect) ScanX(ctx context.Context, v interface{}) {
	if err := xs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (xs *XxxSelect) Strings(ctx context.Context) ([]string, error) {
	if len(xs.fields) > 1 {
		return nil, errors.New("ent: XxxSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := xs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (xs *XxxSelect) StringsX(ctx context.Context) []string {
	v, err := xs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (xs *XxxSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = xs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xxx.Label}
	default:
		err = fmt.Errorf("ent: XxxSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (xs *XxxSelect) StringX(ctx context.Context) string {
	v, err := xs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (xs *XxxSelect) Ints(ctx context.Context) ([]int, error) {
	if len(xs.fields) > 1 {
		return nil, errors.New("ent: XxxSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := xs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (xs *XxxSelect) IntsX(ctx context.Context) []int {
	v, err := xs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (xs *XxxSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = xs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xxx.Label}
	default:
		err = fmt.Errorf("ent: XxxSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (xs *XxxSelect) IntX(ctx context.Context) int {
	v, err := xs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (xs *XxxSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(xs.fields) > 1 {
		return nil, errors.New("ent: XxxSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := xs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (xs *XxxSelect) Float64sX(ctx context.Context) []float64 {
	v, err := xs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (xs *XxxSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = xs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xxx.Label}
	default:
		err = fmt.Errorf("ent: XxxSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (xs *XxxSelect) Float64X(ctx context.Context) float64 {
	v, err := xs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (xs *XxxSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(xs.fields) > 1 {
		return nil, errors.New("ent: XxxSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := xs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (xs *XxxSelect) BoolsX(ctx context.Context) []bool {
	v, err := xs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (xs *XxxSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = xs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xxx.Label}
	default:
		err = fmt.Errorf("ent: XxxSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (xs *XxxSelect) BoolX(ctx context.Context) bool {
	v, err := xs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (xs *XxxSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := xs.sql.Query()
	if err := xs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
