// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"xxx/app/infra/ent/ent/predicate"
	"xxx/app/infra/ent/ent/xxx"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// XxxDelete is the builder for deleting a Xxx entity.
type XxxDelete struct {
	config
	hooks    []Hook
	mutation *XxxMutation
}

// Where appends a list predicates to the XxxDelete builder.
func (xd *XxxDelete) Where(ps ...predicate.Xxx) *XxxDelete {
	xd.mutation.Where(ps...)
	return xd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (xd *XxxDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(xd.hooks) == 0 {
		affected, err = xd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*XxxMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			xd.mutation = mutation
			affected, err = xd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(xd.hooks) - 1; i >= 0; i-- {
			if xd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = xd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, xd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (xd *XxxDelete) ExecX(ctx context.Context) int {
	n, err := xd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (xd *XxxDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: xxx.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: xxx.FieldID,
			},
		},
	}
	if ps := xd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, xd.driver, _spec)
}

// XxxDeleteOne is the builder for deleting a single Xxx entity.
type XxxDeleteOne struct {
	xd *XxxDelete
}

// Exec executes the deletion query.
func (xdo *XxxDeleteOne) Exec(ctx context.Context) error {
	n, err := xdo.xd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{xxx.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (xdo *XxxDeleteOne) ExecX(ctx context.Context) {
	xdo.xd.ExecX(ctx)
}
