// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// XxxesColumns holds the columns for the "xxxes" table.
	XxxesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "number", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// XxxesTable holds the schema information for the "xxxes" table.
	XxxesTable = &schema.Table{
		Name:       "xxxes",
		Columns:    XxxesColumns,
		PrimaryKey: []*schema.Column{XxxesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		XxxesTable,
	}
)

func init() {
}
