// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Fuga is the predicate function for fuga builders.
type Fuga func(*sql.Selector)

// Hoge is the predicate function for hoge builders.
type Hoge func(*sql.Selector)
